name: CI PRs

on:
  pull_request:
    branches:
      - 'main'
      - '0.2.x'
    paths-ignore:
      - '.github/**'

jobs:
  build_and_verify:
    name: Build and Verify
    runs-on: ubuntu-latest
    if: github.repository == 'spring-projects/spring-pulsar'
    steps:
      - uses: actions/checkout@v3
      - uses: spring-io/spring-gradle-build-action@v2
      - name: Build and run unit tests
        run: |
          ./gradlew clean build -x integrationTest --continue --scan
      - name: Create Aggregated Jacoco Report
        if: contains(github.event.pull_request.labels.*.name, 'ci/upload-jacoco')
        run: |
          ./gradlew aggregateJacocoTestReport --info
      - name: Upload Aggregated Jacoco Report
        if: contains(github.event.pull_request.labels.*.name, 'ci/upload-jacoco')
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-results
          path: 'build/reports/jacoco/**/*.*'
          retention-days: 3
      - name: Capture Test Results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '*/build/reports/tests/**/*.*'
          retention-days: 3
  integration_tests:
    needs: [ build_and_verify ]
    runs-on: ubuntu-latest
    if: github.repository == 'spring-projects/spring-pulsar'
    steps:
      - uses: actions/checkout@v3
      - uses: spring-io/spring-gradle-build-action@v2
      - name: Run integration tests
        run: |
          ./gradlew integrationTest --rerun-tasks -DdownloadRabbitConnector=true --scan
      - name: Capture Test Results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '*/build/reports/tests/**/*.*'
          retention-days: 3
  check_samples:
    needs: [ build_and_verify ]
    runs-on: ubuntu-latest
    if: github.repository == 'spring-projects/spring-pulsar'
    steps:
      - uses: actions/checkout@v3
      - uses: spring-io/spring-gradle-build-action@v2
      - name: Run all sample app tests
        env:
          LOCAL_REPOSITORY_PATH: ${{ github.workspace }}/build/publications/repos
          VERSION: ${{ needs.prerequisites.outputs.project_version }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          ./gradlew publishMavenJavaPublicationToLocalRepository
          ./gradlew \
              --init-script ./spring-pulsar-sample-apps/sample-apps-check-ci.gradle \
              -PlocalRepositoryPath="$LOCAL_REPOSITORY_PATH" \
              -PspringPulsarVersion="$VERSION" \
              :runAllSampleTests
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'
      - name: 'Scanned'
        shell: bash
        run: echo "::info ::Scanned"
  done:
    runs-on: ubuntu-latest
    needs: [ build_and_verify, check_samples, scan ]
    steps:
      - name: 'Done'
        shell: bash
        run: echo "::info ::Done"
