name: Prepare Release Notes

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Version to create release notes for'
        required: true
        type: string

jobs:
  prepare_release_notes:
    if: github.repository == 'spring-projects/spring-pulsar'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: spring-io/spring-gradle-build-action@v2
      - name: Install tooling for Github release
        run: |
          curl -sSL -O https://github.com/spring-io/github-changelog-generator/releases/download/v0.0.8/github-changelog-generator.jar
      - name: Create Github release
        env:
          VERSION: ${{ inputs.releaseVersion }}
          RELEASE_NOTES_FILE: ${{runner.temp}}/release_notes.md5
          GH_TOKEN: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}
        run: |
          java -jar github-changelog-generator.jar \
            --spring.config.location=.github/changelog-generator.yml \
            $VERSION $RELEASE_NOTES_FILE
          
          cat $RELEASE_NOTES_FILE
